import Head from 'next/head'

import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import io from 'Socket.IO-client'
let socket;
let i = 1;

export default function Home() {
  const [value, setValue] = useState('')
  const [values, setValues] = useState([])
  const add = () => {
    setValues(prev => [...prev, value])
    setValue('')
    socket.emit('added',value)
  }
  
  useEffect(() => {
    if(i === 1){
      fetch('/api/hello').then(()=>{
        socket = io()
  
        socket.on('connect', () => {
          console.log('connected')
        })
    
        socket.on('upd', msg => {
          setValues(prev=>[...prev,msg]) 
        })
      })
    }
    i++
  }, [])

  

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <input value={value} onChange={e=>setValue(e.target.value)}/>
          <button onClick={add}>add</button>
        </div>
          {values.map((v,i)=>(
            <div key={i}>
              <p>{v}</p>
            </div>
          ))}
        </main>
    </div>
  )
}
